// 1App10Ways/AngularJS/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  todos: string[] = [];
  todoText = '';

  ngOnInit() {
    const exisitngTodos = localStorage.getItem('todos');
    this.todos = JSON.parse(exisitngTodos as string) || [];
  }

  addTodo() {
    this.todos.push(this.todoText);
    localStorage.setItem('todos', JSON.stringify(this.todos));
  }
}

// 1App10Ways/SolidJs/src/App.jsx
import logo from './logo.svg';
import styles from './App.module.css';
import { createSignal, onMount } from "solid-js";

function App() {

  const [todos, setTodos] = createSignal([]);
  let todoText;

  onMount(() => {
    const exisitngTodos = localStorage.getItem('todos');
    setTodos(exisitngTodos ? JSON.parse(exisitngTodos) : []);
  });

  function addTodo(event) {
    event.preventDefault();
    const next = [... todos(), todoText.value];
    setTodos(next);
    localStorage.setItem('todos', JSON.stringify(next));
  }

  return (
    <div>
      <ul>
        {todos().map(todo => (<li key={todo}>{todo}</li>))}  
      </ul>

      <form onSubmit={addTodo}>
        <input type="text" ref={todoText} />
        <input type="submit" value="Add Todo" />
      </form>
    </div>
  );
}

export default App;
