// 1App10Ways/reactjs/src/App.js
import logo from './logo.svg';
import './App.css';
import { useEffect, useRef, useState } from 'react';

function App() {

  const [todos, setTodos] = useState([]);
  const todoText = useRef();

  useEffect(() => {
    const existingTodos = localStorage.getItem('todos');
    setTodos(existingTodos ? JSON.parse(existingTodos) : []);
  }, []);

  function addTodo(event) {
    event.preventDefault();
    const next = [...todos, todoText.current.value];
    setTodos(next);
    localStorage.setItem('todos', JSON.stringify(next));
  }

  return (
    <div>
      <ul>
        {todos.map(todo => (<li key={todo}>{todo}</li>))}
      </ul>
      <form onSubmit={addTodo}>
         <input type="text" placeholder="What need to be done?" ref={todoText} />
         <input type="submit" value="Add Todo"/>
      </form>
    </div>
  );

}

export default App;

// 1App10Ways/SolidJs/src/App.jsx
import logo from './logo.svg';
import styles from './App.module.css';
import { createSignal, onMount } from "solid-js";

function App() {

  const [todos, setTodos] = createSignal([]);
  let todoText;

  onMount(() => {
    const exisitngTodos = localStorage.getItem('todos');
    setTodos(exisitngTodos ? JSON.parse(exisitngTodos) : []);
  });

  function addTodo(event) {
    event.preventDefault();
    const next = [... todos(), todoText.value];
    setTodos(next);
    localStorage.setItem('todos', JSON.stringify(next));
  }

  return (
    <div>
      <ul>
        {todos().map(todo => (<li key={todo}>{todo}</li>))}  
      </ul>

      <form onSubmit={addTodo}>
        <input type="text" ref={todoText} />
        <input type="submit" value="Add Todo" />
      </form>
    </div>
  );
}

export default App;
