// 1App10Ways/svelteJS/src/App.svelte
<script>
	import { onMount } from 'svelte';
import { each } from 'svelte/internal';

	let todos = [];
	let todoText = '';

	onMount(() => {
		const existingTodos = localStorage.getItem('todos');
		todos = JSON.parse(existingTodos) || [];
	});

	function addTodos() {
		todos = [...todos, todoText];
		localStorage.setItem('todos', JSON.stringify(todos));
	}
</script>

<main>
	<ul>
		{#each todos as todo}
			<li>{todo}</li>
		{/each}
	</ul>

	<form on:submit|preventDefault={addTodos}>
		<input bind:value={todoText} placeholder="What needs to be done?">
		<input type="submit" value="Add todo">
	</form>
</main>

<style>
	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	/* h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 4em;
		font-weight: 100;
	} */

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
</style>

// 1App10Ways/reactjs/src/App.js
import logo from './logo.svg';
import './App.css';
import { useEffect, useRef, useState } from 'react';

function App() {

  const [todos, setTodos] = useState([]);
  const todoText = useRef();

  useEffect(() => {
    const existingTodos = localStorage.getItem('todos');
    setTodos(existingTodos ? JSON.parse(existingTodos) : []);
  }, []);

  function addTodo(event) {
    event.preventDefault();
    const next = [...todos, todoText.current.value];
    setTodos(next);
    localStorage.setItem('todos', JSON.stringify(next));
  }

  return (
    <div>
      <ul>
        {todos.map(todo => (<li key={todo}>{todo}</li>))}
      </ul>
      <form onSubmit={addTodo}>
         <input type="text" placeholder="What need to be done?" ref={todoText} />
         <input type="submit" value="Add Todo"/>
      </form>
    </div>
  );

}

export default App;
